<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.9" />
    <PackageReference Include="QuestPDF" Version="2026.7.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApparelPro.Data\ApparelPro.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Reports\ImportExport\Assets\ceylon-chamber-logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Reports\GeneralInventory\" />
    <Folder Include="Services\Implementation\GeneralInventory\" />
    <Folder Include="Services\Implementation\Reports\OrderManagement\" />
    <Folder Include="Services\interfaces\GeneralInventory\" />
    <Folder Include="Services\interfaces\OrderManagement\" />
    <Folder Include="Services\interfaces\Reports\OrderManagement\" />
    <Folder Include="Services\Models\GeneralInventory\" />
    <Folder Include="Services\Models\OrderManagement\ISupplierPurchaseOrder\" />
    <Folder Include="Services\Reports\Models\" />
  </ItemGroup>

</Project>
