// <auto-generated />
using System;
using ApparelPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApparelPro.Data.Migrations
{
    [DbContext(typeof(ApparelProDbContext))]
    [Migration("20240920130033_update-identity-id-in-style-table")]
    partial class updateidentityidinstyletable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.PODetails", b =>
                {
                    b.Property<int>("Buyer")
                        .HasColumnType("int");

                    b.Property<string>("Order")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar");

                    b.Property<string>("LCNo")
                        .IsRequired()
                        .HasMaxLength(23)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("OrderQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("OrderUnit")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<int>("PONo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PONo"));

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Buyer", "Order", "Type", "Style");

                    b.ToTable("PODetails");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.PurchaseOrder", b =>
                {
                    b.Property<int>("BuyerCode")
                        .HasColumnType("int");

                    b.Property<string>("Order")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar");

                    b.Property<string>("BasisCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("BasisValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<int>("GarmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.HasKey("BuyerCode", "Order");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AddressId")
                        .HasColumnType("Guid");

                    b.Property<int?>("AddressType")
                        .HasColumnType("int");

                    b.Property<int?>("BuyerCode")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar");

                    b.Property<bool?>("Default")
                        .HasColumnType("bit");

                    b.Property<string>("PostCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar");

                    b.Property<string>("State")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Bank", b =>
                {
                    b.Property<string>("BankCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LoanLimit")
                        .HasColumnType("money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("SwiftCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("TelephoneNos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("BankCode");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Basis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("ValueAdd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Basis");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Buyer", b =>
                {
                    b.Property<int>("BuyerCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuyerCode"));

                    b.Property<Guid?>("AddressId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CUSDEC")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Fax")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MobileNos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar");

                    b.Property<string>("TelephoneNos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("BuyerCode");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<byte[]>("Flag")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Minor")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Code");

                    b.HasIndex("CountryCode")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.CurrencyConversion", b =>
                {
                    b.Property<string>("FromCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ToCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("FromCurrency", "ToCurrency");

                    b.ToTable("CurrencyConversions");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.CurrencyExchange", b =>
                {
                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("QuoteCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("ExchangeDate")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Rate")
                        .IsRequired()
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("BaseCurrency", "QuoteCurrency", "ExchangeDate")
                        .HasName("PK_CurencyExchange");

                    b.ToTable("CurrencyExchanges");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.GarmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("GarmentTypes");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.StockItem", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("int");

                    b.Property<int>("ItemCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCode"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("StockCode", "ItemCode");

                    b.HasIndex("StockId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<int>("BuyerCode")
                        .HasMaxLength(6)
                        .HasColumnType("int")
                        .HasColumnName("Buyer");

                    b.Property<bool?>("CustomerReturn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("EstimateApprovalDate")
                        .HasColumnType("date");

                    b.Property<string>("EstimateApprovalUserName")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar");

                    b.Property<decimal?>("ExportBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("Exported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ProductionEndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StyleCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Style");

                    b.Property<bool?>("SupplierReturn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TypeCode")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<string>("Unit")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Username")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("BuyerCode", "Order", "TypeCode", "StyleCode")
                        .IsUnique();

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.Registration.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Gender")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KnownAs")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Address", b =>
                {
                    b.HasOne("ApparelPro.Data.Models.References.Buyer", "Buyer")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressId")
                        .HasPrincipalKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Currency", b =>
                {
                    b.HasOne("ApparelPro.Data.Models.References.Country", null)
                        .WithOne()
                        .HasForeignKey("ApparelPro.Data.Models.References.Currency", "CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.StockItem", b =>
                {
                    b.HasOne("ApparelPro.Data.Models.References.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Buyer", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
