using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApparelPro.Data.Migrations
{
    /// <inheritdoc />
    public partial class RenameSupplierPurchaseOrderTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Hand-written as RenameTable (metadata-only, preserves all rows) instead of the
            // DropTable/CreateTable pair the scaffolder generated by default - a straight rename
            // of two C# classes looks identical to "drop the old table, create an unrelated new
            // one" from EF's model-diff perspective, but PODetails/PurchaseOrderHeaders hold real
            // production data (52 and 7 rows respectively) that must not be lost.
            migrationBuilder.RenameTable(
                name: "PODetails",
                newName: "SupplierPurchaseOrderDetails");

            migrationBuilder.DropPrimaryKey(
                name: "PK_PODetails",
                table: "SupplierPurchaseOrderDetails");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SupplierPurchaseOrderDetails",
                table: "SupplierPurchaseOrderDetails",
                columns: new[] { "PONumber", "Buyer", "Order", "Type", "Style", "ItemCode" });

            migrationBuilder.RenameTable(
                name: "PurchaseOrderHeaders",
                newName: "SupplierPurchaseOrders");

            migrationBuilder.DropForeignKey(
                name: "FK_PurchaseOrderHeaders_Currencies_CurrencyCode",
                table: "SupplierPurchaseOrders");

            migrationBuilder.DropPrimaryKey(
                name: "PK_PurchaseOrderHeaders",
                table: "SupplierPurchaseOrders");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SupplierPurchaseOrders",
                table: "SupplierPurchaseOrders",
                column: "PurchaseOrderNumber");

            migrationBuilder.RenameIndex(
                name: "IX_PurchaseOrderHeaders_CurrencyCode",
                table: "SupplierPurchaseOrders",
                newName: "IX_SupplierPurchaseOrders_CurrencyCode");

            migrationBuilder.AddForeignKey(
                name: "FK_SupplierPurchaseOrders_Currencies_CurrencyCode",
                table: "SupplierPurchaseOrders",
                column: "CurrencyCode",
                principalTable: "Currencies",
                principalColumn: "Code",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SupplierPurchaseOrders_Currencies_CurrencyCode",
                table: "SupplierPurchaseOrders");

            migrationBuilder.RenameIndex(
                name: "IX_SupplierPurchaseOrders_CurrencyCode",
                table: "SupplierPurchaseOrders",
                newName: "IX_PurchaseOrderHeaders_CurrencyCode");

            migrationBuilder.DropPrimaryKey(
                name: "PK_SupplierPurchaseOrders",
                table: "SupplierPurchaseOrders");

            migrationBuilder.AddPrimaryKey(
                name: "PK_PurchaseOrderHeaders",
                table: "SupplierPurchaseOrders",
                column: "PurchaseOrderNumber");

            migrationBuilder.RenameTable(
                name: "SupplierPurchaseOrders",
                newName: "PurchaseOrderHeaders");

            migrationBuilder.AddForeignKey(
                name: "FK_PurchaseOrderHeaders_Currencies_CurrencyCode",
                table: "PurchaseOrderHeaders",
                column: "CurrencyCode",
                principalTable: "Currencies",
                principalColumn: "Code",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.DropPrimaryKey(
                name: "PK_SupplierPurchaseOrderDetails",
                table: "SupplierPurchaseOrderDetails");

            migrationBuilder.AddPrimaryKey(
                name: "PK_PODetails",
                table: "SupplierPurchaseOrderDetails",
                columns: new[] { "PONumber", "Buyer", "Order", "Type", "Style", "ItemCode" });

            migrationBuilder.RenameTable(
                name: "SupplierPurchaseOrderDetails",
                newName: "PODetails");
        }
    }
}
