// <auto-generated />
using System;
using ApparelPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApparelPro.Data.Migrations
{
    [DbContext(typeof(ApparelProDbContext))]
    [Migration("20260620090651_AlterPODetailsPONoToStringAndAddOrderwsieStockAndOrderwiseStockMaster")]
    partial class AlterPODetailsPONoToStringAndAddOrderwsieStockAndOrderwiseStockMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.ColorSizeDetails", b =>
                {
                    b.Property<int>("BuyerCode")
                        .HasColumnType("int")
                        .HasColumnName("Buyer");

                    b.Property<string>("Order")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Order");

                    b.Property<int>("TypeCode")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<string>("StyleCode")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Style");

                    b.Property<string>("Color")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Color");

                    b.Property<string>("Size")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Size");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Ratio");

                    b.HasKey("BuyerCode", "Order", "TypeCode", "StyleCode", "Color", "Size");

                    b.ToTable("ColorSizeDetails");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.MaterialConsumption.ItemFeature", b =>
                {
                    b.Property<string>("FeatureCode")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("FeatureCode");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Description");

                    b.HasKey("FeatureCode");

                    b.ToTable("ItemFeatures", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.MaterialConsumption.OrderItem", b =>
                {
                    b.Property<string>("StockCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("StockCode");

                    b.Property<string>("ItemCode")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ItemCode");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Description");

                    b.HasKey("StockCode", "ItemCode");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.MaterialConsumption.OrderItemFeature", b =>
                {
                    b.Property<string>("StockCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("StockCode");

                    b.Property<string>("ItemCode")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ItemCode");

                    b.Property<decimal?>("CostPerUnit")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("CostPerUnit");

                    b.Property<string>("Feature1Type")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature1");

                    b.Property<string>("Feature2Type")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature2");

                    b.Property<string>("Feature3Type")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature3");

                    b.Property<string>("Feature4Type")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature4");

                    b.HasKey("StockCode", "ItemCode");

                    b.ToTable("OrderItemFeatures", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.MaterialConsumption.StyleMaterialConsumptionLedger", b =>
                {
                    b.Property<int>("BuyerCode")
                        .HasColumnType("int")
                        .HasColumnName("Buyer");

                    b.Property<string>("Order")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Order");

                    b.Property<int>("TypeCode")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<string>("StyleCode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Style");

                    b.Property<string>("Color")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("Color");

                    b.Property<string>("Size")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Size");

                    b.Property<string>("StockCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("StockCode");

                    b.Property<string>("ItemCode")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ItemCode");

                    b.Property<string>("Feature1")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature1");

                    b.Property<string>("Feature2")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature2");

                    b.Property<string>("Feature3")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature3");

                    b.Property<string>("Feature4")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature4");

                    b.Property<bool>("CalculateConsumption")
                        .HasColumnType("bit")
                        .HasColumnName("CalculateConsumption");

                    b.Property<string>("ConsumptionUnit")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ConsumptionUnit");

                    b.Property<bool>("IsAdditionalCost")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdditionalCost");

                    b.Property<string>("ItemUnit")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ItemUnit");

                    b.Property<decimal>("PercentageAllowance")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("PercentageAllowance");

                    b.Property<decimal>("QuantityPerGarment")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("QuantityPerGarment");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("StoreCode");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("SupplierCode");

                    b.Property<decimal>("TotalConsumption")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("TotalConsumption");

                    b.HasKey("BuyerCode", "Order", "TypeCode", "StyleCode", "Color", "Size", "StockCode", "ItemCode", "Feature1", "Feature2", "Feature3", "Feature4");

                    b.ToTable("StyleMaterialConsumptionLedger", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.MaterialConsumption.StyleMaterialCostProfile", b =>
                {
                    b.Property<int>("BuyerCode")
                        .HasColumnType("int")
                        .HasColumnName("Buyer");

                    b.Property<string>("Order")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Order");

                    b.Property<int>("TypeCode")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<string>("StyleCode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Style");

                    b.Property<string>("StockCode")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("StockCode");

                    b.Property<string>("ItemCode")
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ItemCode");

                    b.Property<string>("Feature1")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature1");

                    b.Property<string>("Feature2")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature2");

                    b.Property<string>("Feature3")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature3");

                    b.Property<string>("Feature4")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("Feature4");

                    b.Property<decimal>("BalanceQuantity")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("BalanceQuantity");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CurrencyCode");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Description");

                    b.Property<string>("ItemUnit")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ItemUnit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("Price");

                    b.HasKey("BuyerCode", "Order", "TypeCode", "StyleCode", "StockCode", "ItemCode", "Feature1", "Feature2", "Feature3", "Feature4");

                    b.ToTable("StyleMaterialCostProfiles", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.PODetailItem", b =>
                {
                    b.Property<string>("PONumber")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PONumber");

                    b.Property<int>("Buyer")
                        .HasColumnType("int")
                        .HasColumnName("Buyer");

                    b.Property<string>("Order")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Order");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<string>("Style")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Style");

                    b.Property<string>("ItemCode")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ItemCode");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Balance");

                    b.Property<DateTime?>("ExportDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ExportDate");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LCNo")
                        .HasColumnType("varchar(23)")
                        .HasColumnName("LCNo");

                    b.Property<decimal>("OrderQuantity")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("OrderQuantity");

                    b.Property<string>("OrderUnit")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("OrderUnit");

                    b.Property<string>("RefNo")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("RefNo");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("PONumber", "Buyer", "Order", "Type", "Style", "ItemCode");

                    b.ToTable("PODetails", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderManagement.PurchaseOrder", b =>
                {
                    b.Property<int>("BuyerCode")
                        .HasColumnType("int");

                    b.Property<string>("Order")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar");

                    b.Property<string>("BasisCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("BasisValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<int>("GarmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.HasKey("BuyerCode", "Order");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderwiseInventory.OrderwiseStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerCode")
                        .HasColumnType("int")
                        .HasColumnName("BuyerCode");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ItemCode");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Order");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("OrderedQuantity");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("StoreCode");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Unit");

                    b.HasKey("Id");

                    b.ToTable("OrderwiseStocks", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.OrderwiseInventory.OrderwiseStockMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerCode")
                        .HasColumnType("int")
                        .HasColumnName("BuyerCode");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Currency");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ItemCode");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Order");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("OrderedQuantity");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("Price");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Unit");

                    b.HasKey("Id");

                    b.ToTable("OrderwiseStockMasters", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AddressType")
                        .HasColumnType("int");

                    b.Property<string>("BankCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("BuyerCode")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar");

                    b.Property<bool?>("Default")
                        .HasColumnType("bit");

                    b.Property<string>("PostCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar");

                    b.Property<string>("State")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BankCode");

                    b.HasIndex("BuyerCode");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Bank", b =>
                {
                    b.Property<string>("BankCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LoanLimit")
                        .HasColumnType("money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar");

                    b.Property<string>("TelephoneNos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("BankCode");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Basis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("ValueAdd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Basis");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Buyer", b =>
                {
                    b.Property<int>("BuyerCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuyerCode"));

                    b.Property<string>("CUSDEC")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Fax")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MobileNos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar");

                    b.Property<string>("TelephoneNos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("BuyerCode");

                    b.HasIndex("BuyerCode");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<byte[]>("Flag")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Minor")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Code");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.CurrencyConversion", b =>
                {
                    b.Property<string>("FromCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ToCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("FromCurrency", "ToCurrency");

                    b.ToTable("CurrencyConversions");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.CurrencyExchange", b =>
                {
                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("QuoteCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("ExchangeDate")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("BaseCurrency", "QuoteCurrency", "ExchangeDate")
                        .HasName("PK_CurencyExchange");

                    b.ToTable("CurrencyExchanges");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id", "CountryCode");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.GarmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("GarmentTypes");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.StockItem", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("int");

                    b.Property<int>("ItemCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCode"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("StockCode", "ItemCode");

                    b.HasIndex("StockId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<int>("BuyerCode")
                        .HasMaxLength(6)
                        .HasColumnType("int")
                        .HasColumnName("Buyer");

                    b.Property<string>("ColorRatio")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ColorRatio");

                    b.Property<bool?>("CustomerReturn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("EstimateApprovalDate")
                        .HasColumnType("date");

                    b.Property<string>("EstimateApprovalUserName")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal?>("ExportBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("Exported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ProductionEndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SizeRatio")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("SizeRatio");

                    b.Property<string>("StyleCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Style");

                    b.Property<bool?>("SupplierReturn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TypeCode")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<string>("Unit")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Username")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerCode", "Order", "TypeCode", "StyleCode")
                        .IsUnique();

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Supplier", b =>
                {
                    b.Property<int>("SupplierCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierCode"));

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fax")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("MobileNos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("TelephoneNos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("SupplierCode");

                    b.HasIndex("SupplierCode");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.UnitConversion", b =>
                {
                    b.Property<string>("FromUnit")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("FromUnit");

                    b.Property<string>("ToUnit")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ToUnit");

                    b.Property<decimal>("Measure")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Measure");

                    b.HasKey("FromUnit", "ToUnit");

                    b.ToTable("UnitConversion", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.Registration.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Bank")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Gender")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KnownAs")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApparelPro.WebApi.APIModels.OrderManagement.GarmentTypeItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GarmentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("GarmentTypeId");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ItemCode");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("Quantity");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("StockCode");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Unit");

                    b.HasKey("Id");

                    b.HasIndex("GarmentTypeId");

                    b.ToTable("GarmentTypeItems", (string)null);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Address", b =>
                {
                    b.HasOne("ApparelPro.Data.Models.References.Bank", null)
                        .WithMany("Addresses")
                        .HasForeignKey("BankCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ApparelPro.Data.Models.References.Buyer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("BuyerCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.StockItem", b =>
                {
                    b.HasOne("ApparelPro.Data.Models.References.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ApparelPro.WebApi.APIModels.OrderManagement.GarmentTypeItems", b =>
                {
                    b.HasOne("ApparelPro.Data.Models.References.GarmentType", "GarmentType")
                        .WithMany()
                        .HasForeignKey("GarmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GarmentType");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Bank", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("ApparelPro.Data.Models.References.Buyer", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
